# Generated by ./update.sh - do not update manually!
# Last updated: 2026-06-08
{
  linux-version = "12.1.2.25882";
  x86_64-linux = {
    url = "https://pubwps-wps365-obs.wpscdn.cn/download/Linux/25882/wps-office_12.1.2.25882.AK.preread.sw.365_667345_amd64.deb";
    hash = "sha256-peVPxle1D+5NfAj0TaKhIIDRrOqYV6HbSHfrM1XdJjE=";
  };
  aarch64-linux = {
    url = "https://pubwps-wps365-obs.wpscdn.cn/download/Linux/25882/wps-office_12.1.2.25882.AK.preread.sw.365_667348_arm64.deb";
    hash = "sha256-Xog0+TJaYjqPVAoptKOzHNJPrfXdNKDEc0qYgRcRnyA=";
  };
  loongarch64-linux = {
    url = "https://pubwps-wps365-obs.wpscdn.cn/download/Linux/25882/wps-office_12.1.2.25882.AK.preread.sw.365_667352_loongarch64.deb";
    hash = "sha256-oIyDqTQLj9J7vyDFkS28GlfLiyyg5AmdOEuYH2kibCY=";
  };
}
