# Generated by ./update.sh - do not update manually!
# Last updated: 2026-03-23
{
  linux-version = "12.1.2.24730";
  x86_64-linux = {
    url = "https://pubwps-wps365-obs.wpscdn.cn/download/Linux/24730/wps-office_12.1.2.24730.AK.preread.sw_644359_amd64.deb";
    hash = "sha256-CNVlVLd7/vl7jhDQImAHCPCR5vtz99DTHCsu6yeswRw=";
  };
  aarch64-linux = {
    url = "https://pubwps-wps365-obs.wpscdn.cn/download/Linux/24730/wps-office_12.1.2.24730.AK.preread.sw_644358_arm64.deb";
    hash = "sha256-oj28gypiX9FcZqCR1Czdmg+Orv5r3eDEprSLuy4lu0A=";
  };
}
