#!/usr/bin/env nix-shell
#!nix-shell -i bash -p bash coreutils gnused nix-prefetch-git

set -euo pipefail

cd "$(dirname "$0")"

SOURCES_FILE="./sources.nix"

VERSION="12.1.2.24730"
BUILD_NUMBER="24730"

URL_AMD64="https://pubwps-wps365-obs.wpscdn.cn/download/Linux/${BUILD_NUMBER}/wps-office_${VERSION}.AK.preread.sw_644359_amd64.deb"
URL_ARM64="https://pubwps-wps365-obs.wpscdn.cn/download/Linux/${BUILD_NUMBER}/wps-office_${VERSION}.AK.preread.sw_644358_arm64.deb"

echo "Fetching new hash for x86_64-linux version ${VERSION}..."
HASH_AMD64_OUTPUT=$(nix-prefetch-url --name "wps-office_${VERSION}_amd64.deb" "$URL_AMD64" 2>&1)
HASH_AMD64=$(echo "$HASH_AMD64_OUTPUT" | tail -n 1)
SRI_HASH_AMD64=$(nix hash to-sri --type sha256 "$HASH_AMD64")

echo "New hash for x86_64-linux: $SRI_HASH_AMD64"

echo "Fetching new hash for aarch64-linux version ${VERSION}..."
HASH_ARM64_OUTPUT=$(nix-prefetch-url --name "wps-office_${VERSION}_arm64.deb" "$URL_ARM64" 2>&1)
HASH_ARM64=$(echo "$HASH_ARM64_OUTPUT" | tail -n 1)
SRI_HASH_ARM64=$(nix hash to-sri --type sha256 "$HASH_ARM64")

echo "New hash for aarch64-linux: $SRI_HASH_ARM64"

cat > "$SOURCES_FILE" << EOF
# Generated by ./update.sh - do not update manually!
# Last updated: $(date +%Y-%m-%d)
{
  linux-version = "${VERSION}";
  x86_64-linux = {
    url = "${URL_AMD64}";
    hash = "${SRI_HASH_AMD64}";
  };
  aarch64-linux = {
    url = "${URL_ARM64}";
    hash = "${SRI_HASH_ARM64}";
  };
}
EOF

echo "Updated $SOURCES_FILE"
