#!/usr/bin/env nix-shell
#!nix-shell -i bash -p bash coreutils gnused nix-prefetch-git

set -euo pipefail

cd "$(dirname "$0")"

SOURCES_FILE="./sources.nix"

VERSION="12.1.2.24722"
BUILD_NUMBER="24722"
URL="https://pubwps-wps365-obs.wpscdn.cn/download/Linux/${BUILD_NUMBER}/wps-office_${VERSION}.AK.preread.sw_612423_amd64.deb"

echo "Fetching new hash for version ${VERSION}..."
HASH_OUTPUT=$(nix-prefetch-url --name "wps-office_${VERSION}.deb" "$URL" 2>&1)
HASH=$(echo "$HASH_OUTPUT" | tail -n 1)

echo "New hash: $HASH"

cat > "$SOURCES_FILE" << EOF
# Generated by ./update.sh - do not update manually!
# Last updated: $(date +%Y-%m-%d)
{
  linux-version = "${VERSION}";
  x86_64-linux = {
    url = "${URL}";
    hash = "${HASH}";
  };
}
EOF

echo "Updated $SOURCES_FILE"
