# Generated by ./update.sh - do not update manually!
# Last updated: 2026-03-03
{
  linux-version = "12.1.2.24722";
  x86_64-linux = {
    url = "https://pubwps-wps365-obs.wpscdn.cn/download/Linux/24722/wps-office_12.1.2.24722.AK.preread.sw_612423_amd64.deb";
    hash = "sha256-aY4drb0vTfi9HO3N5LgB3GLZu9Ulg7dlBGtL+78FJIg=";
  };
}
