# Generated by ./update.sh - do not update manually!
# Last updated: 2026-06-08
{
  linux-version = "12.1.2.25882";
  darwin-version = "12.1.26016";
  x86_64-linux = {
    url = "https://wps-linux-personal.wpscdn.cn/wps/download/ep/Linux2023/25882/wps-office_12.1.2.25882.AK.preread.sw.Personal_662820_amd64.deb";
    hash = "sha256-ZdYtB83mGbnbjh7wHRAt37QfZ1F/5eoFUcZYTNhGGUc=";
  };
  x86_64-darwin = {
    url = "https://package.mac.wpscdn.cn/mac_wps_pkg/12.1.26016/WPS_Office_12.1.26016(26016)_x64.dmg";
    hash = "sha256-pyjW1cUKX7RRFDQo2ik2L57fIwixLj0XqHMYTe4aE3g=";
  };
  aarch64-darwin = {
    url = "https://package.mac.wpscdn.cn/mac_wps_pkg/12.1.26016/WPS_Office_12.1.26016(26016)_arm64.dmg";
    hash = "sha256-vlT96ROqB/6Jt/x60Zeh6B4MtN2NGyn5PWv9pNafF/8=";
  };
}
